# Generated by Django 3.0.5 on 2020-09-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'Large Machine'), ('COFFEE_MACHINE_SMALL', 'Small Machine'), ('ESPRESSO_MACHINE', 'Espresso Machine')], default='COFFEE_MACHINE_LARGE', max_length=20)),
                ('brand_model', models.CharField(choices=[('BASE_MODEL', 'Base Model'), ('PREMIUM_MODEL', 'Premium Model'), ('DELUXE_MODEL', 'Deluxe Model')], default='BASE_MODEL', max_length=20)),
                ('water_line', models.BooleanField(default=False)),
            ],
        ),
    ]
