# Generated by Django 3.0.5 on 2020-09-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_POD_LARGE', 'Large Pod'), ('COFFEE_POD_SMALL', 'Small Pod'), ('ESPRESSO_POD', 'Espresso Pod')], default='COFFEE_POD_LARGE', max_length=20)),
                ('coffee_flavor', models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'vanilla'), ('COFFEE_FLAVOR_CARAMEL', 'caramel'), ('COFFEE_FLAVOR_PSL', 'psl'), ('COFFEE_FLAVOR_MOCHA', 'mocha'), ('COFFEE_FLAVOR_HAZELNUT', 'hazelnut')], default='COFFEE_FLAVOR_VANILLA', max_length=30)),
                ('pack_size', models.CharField(choices=[('1 dozen (12)', '1 dozen'), ('3 dozen (36)', '3 dozen'), ('5 dozen (60)', '5 dozen'), ('7 dozen (84)', '7 dozen')], default='1 dozen (12)', max_length=12)),
            ],
        ),
    ]
