# Generated by Django 3.0.5 on 2020-09-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_pods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepod',
            name='coffee_flavor',
            field=models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'vanilla'), ('COFFEE_FLAVOR_CARAMEL', 'caramel'), ('COFFEE_FLAVOR_PSL', 'psl'), ('COFFEE_FLAVOR_MOCHA', 'mocha'), ('COFFEE_FLAVOR_HAZELNUT', 'hazelnut')], default='COFFEE_FLAVOR_VANILLA', max_length=30),
        ),
    ]
